name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
    paths:
      - apps/api/**
  workflow_dispatch:

jobs:
      push-app-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './apps/api'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3

          - name: 'Set up Docker Buildx'
            uses: docker/setup-buildx-action@v3

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: Lowercase Repo Owner
            run: |
              echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
            env:
              GITHUB_REPOSITORY_OWNER: '${{ github.repository_owner }}'

          - name: 'Build and Push Image'
            uses: docker/build-push-action@v6
            with:
              context: ./apps/api
              push: true
              tags: ghcr.io/${{ env.REPO_OWNER }}/firecrawl:latest
              platforms: linux/amd64,linux/arm64
              cache-from: type=registry,ref=ghcr.io/${{ env.REPO_OWNER }}/firecrawl:buildcache
              cache-to: type=registry,ref=ghcr.io/${{ env.REPO_OWNER }}/firecrawl:buildcache,mode=max