name: Deploy Playwright to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
    paths:
      - apps/playwright-service-ts/**
  workflow_dispatch:

jobs:
      push-app-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './apps/playwright-service-ts'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: 'Build Inventory Image'
            run: |
              REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
              docker buildx build . \
                --platform linux/amd64,linux/arm64 \
                --tag ghcr.io/${REPO_OWNER}/playwright-service:latest \
                --push