name: JS SDK Test Suite

on:
  pull_request:
    branches:
      - main
    paths:
      - apps/js-sdk/firecrawl/**

env:
  TEST_API_KEY: ${{ secrets.TEST_API_KEY }}

jobs:
  test:
    name: Run tests
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: './apps/js-sdk/firecrawl/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
        working-directory: ./apps/js-sdk/firecrawl
      - name: Build
        run: pnpm run build
        working-directory: ./apps/js-sdk/firecrawl
      - name: Run tests
        run: pnpm run test
        working-directory: ./apps/js-sdk/firecrawl
